### ISSUE TITLE
scalebar issuse

### ISSUE THREAD

**Issue by alissa777** [by256/imagedataextractor#1]
<img width="873" alt="Screenshot 2021-04-22 at 10 02 41" src="https://user-images.githubusercontent.com/82408734/115688970-8aba2480-a353-11eb-81a9-4b49e5772609.png">
<img width="1061" alt="Screenshot 2021-04-22 at 09 46 12" src="https://user-images.githubusercontent.com/82408734/115688977-8c83e800-a353-11eb-974e-1c53e54ff615.png">
Hi 
My name is Alissa and I have been working on this tool for weeks. 
I followed the instruction of usage and downloaded the latest version of the tool, but theres still some issues in extraction. 
As for the test image(first image), I got value error called zero-size array. After I imput another image from the scalebar folder, It showed another error. However I put an image called example, the extraction was success and I got 8 images.  
Could you please have a look at my issues? 

Thank you!

**Comment by by256** [comment]
Hi,

Thanks for your interest in imagedataextractor. I've tried both examples and the issues are as follows.

1. The issue is that you copied and pasted the code from the example jupyter notebook. In the notebook example, the size of the input image is larger than the image in your first example. This means that when you index your input image with [700:, 700:] to obtain the scalebar region, you get an error, because the image isn't as big. Simply remove this indexing

`plt.imshow(sb_image)`

or replace the indices with the correct ones for your image,

`plt.imshow(sb_image[X:, Y:])`

The correct indices will differ for different images.

2. In this example, scalebar detection has failed and the scalebar is not found, meaning there are no scalebar contours to plot. You should be able to verify this by looking at the values of `sb_text` and `conversion`, which should both be `None` in this case.

I hope this helps. Please star the repo if you find the library useful :)

Batuhan

**Comment by alissa777** [comment]
Hi,
Thank you for the reply!
It does help in first case.
