### ISSUE TITLE
 list object has no attribute segmentation

### ISSUE THREAD

**Issue by under-score** [by256/imagedataextractor#11]
I can read the image file
```
data = ide.extract(image_path)
```
and get a list of [EMData,EMData...] but any further action
```
seg = data.segmentation
uncertainty = data.uncertainty
```
fails as the  'list' object has no attribute 'segmentation'.

BTW as I am mainly interested in segmentation without downstream analysis, isn't there any option for that?

**Comment by by256** [comment]
Hi,

I won't be able to look into this until I'm back at a computer on Monday, but there is a way to use the segmentation model by itself outside of a data extraction context. You can find some details here:

https://www.imagedataextractor.org/docs/segmentation

**Comment by under-score** [comment]
excellent documentation - my second question is already been answered. Wish you a nice weekend!

**Comment by by256** [comment]
I just realised what was causing your initial error.

```python
data = ide.extract(image_path)
```

returns a `list` of EMData objects (since an input image could contain a panel of several EM images which are split and processed individually) and data.segmentation will not work. 

You need to either iterate through each element of the list and access their attributes individually:

```python
for datum in data:
    seg = datum.segmentation
    uncertainty = datum.uncertainty
```

or access each one individually by indexing the list, i.e.,:

```python
seg = data[0].segmentation
uncertainty = data[0].uncertainty
```

Hope this helps.
