### ISSUE TITLE
The scale bar of some images still fails to detect

### ISSUE THREAD

**Issue by wzy283** [by256/imagedataextractor#2]
Hi, I installed the latest version of imagedataextractor (2.0.4) and run the same codes as example. I found some sample images' scale bar could be detected, but some still failed. I have attached my codes and results below. I am currently learning this program, but I got stuck in the scale bar detection, I hope I can discuss this issue with you. Many thanks.
[screenshot.docx](https://github.com/by256/imagedataextractor/files/6357144/screenshot.docx)

**Comment by by256** [comment]
Hi,

Thanks for your interest in imagedataextractor.

Currently, scalebar detection is not perfect and fails in many seemingly straightforward cases. This is due to the underlying optical character recognition model used to read the scalebars. I have plans to improve this model by fine-tuning it on a larger set of scalebar images, but I haven't got round to it yet.

Although it can be tedious, my suggestion in cases where scalebar detection fails is to manually measure the scalebar in pixels and calculate the conversion this way. This is what I have been doing in my work for images where scalebar detection fails.

I hope this helps. Please star the repo if you find the library useful :)

Batuhan

**Comment by wzy283** [comment]
Okay, I will try to manually change the axis and look forward to your release of the new version.
