### ISSUE TITLE
cvDrawContours

### ISSUE THREAD

**Issue by alissa777** [by256/imagedataextractor#3]
Hi,

My name is Alissa.

After I checked the figures and changed them to None. I got an error that happend to most of the images I imput.

But my mate told me that she changed some code to avoid it. I dont know how to get it running successfully without this error. 

Thank you for helping me!

<img width="987" alt="Screenshot 2021-04-24 at 09 09 22" src="https://user-images.githubusercontent.com/82408734/115952425-b9fc9d00-a4dd-11eb-80cc-d6fc80a5834b.png">
<img width="855" alt="Picture 1" src="https://user-images.githubusercontent.com/82408734/115952452-e57f8780-a4dd-11eb-8ada-c1a6ba29c74a.png">

**Comment by by256** [comment]
I think you misunderstood my previous comment. Setting `sb_text` and `conversion` to `None` will not solve the problem. I meant that these values are `None` because scalebar detection has failed. Therefore, there are no scalebar contours to plot. There is nothing you can do in this case.

If you really need the scalebar conversion (not contours), I would suggest you do what I recommended [here](https://github.com/by256/imagedataextractor/issues/2#issuecomment-824711198).

Batuhan

**Comment by alissa777** [comment]
Thank you for your reply.
